### ISSUE TITLE
rename file

### ISSUE THREAD

**Issue by jackhwl** [LizzyYao/PythonPractice#1]
rename all python file using format: ##_filename.py

**Comment by LizzyYao** [comment]
I've done. Mr. Huang

**Comment by jackhwl** [comment]
if you compaire those two pages, you only finished 13 practices, how come you got 14 #? besides the number didn't match the sequence of the daily pracetice.

https://github.com/LizzyYao/PythonPractice
http://www.programiz.com/python-programming/examples

**Comment by LizzyYao** [comment]
You are way too picky.
First question, I did 2 codes for leapyearbefore and after I tried to use
def. so I saved both. I don't want to delete either of them since I need
them for my future reference. I'll continue when I get time to fix the
issue and meet your reqirement on "define".
Second question: these codes are too easy for professional use and may not
be reviewed in the future, does it really matter if I don't put them in
order of completion date?

**Comment by jackhwl** [comment]
1.you need combine two code for leapyearbefore to one file, exactly make the second file change to the first one, then delete the second one.
2. the only reason put ## in front of the file not end of the filename is to make it sort automatically, if you don't put it right ## it make the ## meaningless. the only person going to see these code in the future is yourself, make it clean and easy to understand and find is for yourself benefit not others,
