### ISSUE TITLE
Identification, Authentication, and Authorization

### ISSUE THREAD

**Issue by jackhwl** [LizzyYao/PythonPractice#22]
Figure it out what is Identification, Authentication, and Authorization.

**Comment by LizzyYao** [comment]
我把它都当同义词用了

**Comment by LizzyYao** [comment]
I read some material, I am trying to explain it with my own words.
Identification: you claim who you are. In computer and network environment, typically it's the Username professing step.
Authentication: to prove you are really the person you claimed to be. typically you provide a password which was already set up and saved in the system. it's like the secret between you and the system so that you can tell the system you are the right user.
Authorization: this one I am familiar with even though I don't use it often under IT environment. my company is dealing with confidential records, only people who are authorized by the company record officer or owner can get access to the company's records, and they have different level of accessing. similarly, authorization is the level of access the system issued you initially (it's changable). Basically it means what you can do with the system after you pass the identification and authentication steps.
